### PR TITLE
account.js template literal fix

### PR DESCRIPTION
**Pull request by Dpschu2**
#### What?

line 414 of account.js should have a template literal

#### Requirements

- [ ] CHANGELOG.md entry added (required for code changes only)

#### Tickets / Documentation

Add links to any relevant tickets and documentation.

- [Link 1](http://example.com)
- ...

#### Screenshots (if appropriate)

Attach images or add image links here.

Example Image

### CODE REVIEW

**Review by bc-yevhenii-buliuk — APPROVED** [review]

**Review by bc-vlad-dlogush — APPROVED** [review]

**Comment by bc-vlad-dlogush** [comment]
@Dpschu2 Could you add the CHANGELOG.md?

**Comment by Dpschu2** [comment]
Changelog added

**Comment by bc-vlad-dlogush** [comment]
These changes will go into the next release, so we add as a draft, like this:
```
## Draft
- Account.js - Fixed jquery selector to be template literal [#2464](https://github.com/bigcommerce/cornerstone/pull/2464)

```

**Review by Dpschu2 — COMMENTED** [review]
changelog fix

**Comment by Dpschu2** [comment]
Thanks for letting me know. That is updated

**Pull request merged**
