### PR TITLE
CP-2383 Make cornerstone theme editor menu items to be easier to use

### PR DESCRIPTION
**Pull request by deepa2083**
Revamping the cornerstone theme editor menu options so it is easier to use.
Attaching the new bundle here for testing. 
This will cause test failures and I have another PR that fixes the failures
 
@bigcommerce/cp-dt @mcampa @bigcommerce/stencil-team @bc-ranji 
New bundle here:
[Cornerstone-1.9.3.zip](https://github.com/bigcommerce/cornerstone/files/1361079/Cornerstone-1.9.3.zip)

Testing screenshots:
Before the change (existing)
screen shot 2017-10-05 at 12 16 06 pm
screen shot 2017-10-05 at 12 15 56 pm

After update:
screen shot 2017-10-05 at 12 17 39 pm
screen shot 2017-10-05 at 12 17 25 pm

### CODE REVIEW

**Comment by mcampa** [comment]
Can you please add the spaces back?
no need to removed the spaces and makes the PR easier to review.

**Comment by deepa2083** [comment]
@mcampa - this id - container-border-global-color-dark has been removed. Please advice if this is ok. 
looks like it is not used in code.

**Comment by mcampa** [comment]
I'm not sure if that is good or bad, that config value is used here https://github.com/bigcommerce/cornerstone/blob/32575cc50534b9f24fbddfee6524d67ff728ef58/assets/scss/settings/global/container/_container.scss#L19

Remember, every field removed from the schema file will prevent customers from changing the configuration value in Theme Editor.

**Comment by bc-ranji** [comment]
💚

**Pull request merged**
