### PR TITLE
fix(payment): PAYPAL-1863 deleted non-working code

### PR DESCRIPTION
**Pull request by bc-nick**
#### What?

Removed non-working "Display Style" feature.

#### Requirements

- [x] CHANGELOG.md entry added (required for code changes only)

#### Tickets / Documentation

According to task: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1863

#### Screenshots (if appropriate)

Screenshot 2022-12-30 at 14 54 20

[PAYPAL-1863]: https://bigcommercecloud.atlassian.net/browse/PAYPAL-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bc-yevhenii-buliuk** [comment]
@bc-nick could you also check the `config.json` file, maybe we should also remove the `"paymentbuttons-paypal-layout"` key if it's no longer used?

**Comment by bc-nick** [comment]
> @bc-nick could you also check the `config.json` file, maybe we should also remove the `"paymentbuttons-paypal-layout"` key if it's no longer used?

@bc-yevhenii-buliuk thanks. yes this key is not needed. i removed

**Review by bc-yevhenii-buliuk — APPROVED** [review]

**Comment by bc-yevhenii-buliuk** [comment]
@bc-nick LGTM. Сould you also merge the two commits into one before merging into the master? Thanks!

**Comment by bc-nick** [comment]
> @bc-nick LGTM. Сould you also merge the two commits into one before merging into the master? Thanks!

@bc-yevhenii-buliuk  yeap, i will make **squash and merge**
As i understood your approval is enough for merge?

**Comment by bc-yevhenii-buliuk** [comment]
> > @bc-nick LGTM. Сould you also merge the two commits into one before merging into the master? Thanks!
> 
> @bc-yevhenii-buliuk yeap, i will make **squash and merge** As i understood your approval is enough for merge?

@bc-nick merge requires at least 2 approvals, so yep, you can merge.

**Pull request merged**
