### PR TITLE
Fix duplicate IDs occurrence in product options in certain situations

### PR DESCRIPTION
**Pull request by flair-duncan**
#### What?

In certain circumstances, product option elements end up with the same ID causing a clash, stopping some options being selected.

Each option component has been given a descriptive ID to prevent the clash. As the add to cart action relies on the name attribute, this does not interfere with the cart system.

#### Screenshots

[Video of issue before changes](https://www.useloom.com/share/1e740a49826f44cdbd56f81bd01bd7d3)

[Video after changes](https://www.useloom.com/share/9fe6d969da9445da91532da6f301de23)

### CODE REVIEW

**Comment by flair-duncan** [comment]
@junedkazi sorry, I messed up my squash as there were a couple more commits to the master while I was working on it, it was quicker to do another PR.

**Comment by bookernath** [comment]
@flair-duncan do you have an example of duplicate IDs you can show, or some replication steps to get to such a state?

**Comment by flair-duncan** [comment]
@bookernath we noticed this occurring on our own theme, and traced it back to the option components in Stencil. If you look at our theme store demo site on [this page](http://22-savile-row-classic-demo.mybigcommerce.com/suits/the-berkeley-sports-jacket/) you can replicate the ID clash by clicking the color swatches.

Clicking the black swatch will select the "Chest Size" option.

I've used this same data with Cornerstone and the same thing happens.

If you want me to create an API key so you can use that store data, let me know. 👍

**Comment by mattolson** [comment]
@Ubersmake Can you test this?

**Comment by junedkazi** [comment]
@flair-duncan sorry for the delay can you rebase this PR & move the change log into the new draft section please.

**Comment by junedkazi** [comment]
@flair-duncan looks like the rebase has gone wrong.

**Comment by flair-duncan** [comment]
@junedkazi hmm, I'll sort it out over the weekend...

**Comment by junedkazi** [comment]
@flair-duncan this looks good to me. Can you please squash your commits into a single one please.

**Comment by flair-duncan** [comment]
@junedkazi I've got absolutely no idea why it's just done that, I successfully rebased and squashed at my end... I'm just going to create a clean PR for you to save time. Sorry 😞

**Comment by junedkazi** [comment]
@flair-duncan did u get a chance to look into this issue ?

**Comment by junedkazi** [comment]
closed in favor of https://github.com/bigcommerce/cornerstone/pull/1261

**Pull request closed without merging**
