### PR TITLE
feat(customers): CUST-1837 Add reCAPTCHA to password reset for Corner…

### PR DESCRIPTION
**Pull request by huntario**
…sone

#### What?

This is to add component arrangement styling to accommodate  - https://github.com/bigcommerce/bigcommerce/pull/44642

#### Requirements

- [x] CHANGELOG.md entry added (required for code changes only)

#### Tickets / Documentation

- [CUST-1837](https://jira.bigcommerce.com/browse/CUST-1837?filter=-3

#### Screenshots (if appropriate)

https://user-images.githubusercontent.com/5630999/151110906-d6962f2d-bc4f-4d5f-b15e-798dca1ecece.mov

https://user-images.githubusercontent.com/5630999/151111090-79424889-db74-45c4-ad28-c8bf63d31674.mov

### CODE REVIEW

**Comment by BC-krasnoshapka** [comment]
hi @huntario 
changes in your PR are failing the bundling test - https://github.com/bigcommerce/cornerstone/runs/4976141414?check_suite_focus=true
can you please check it?

**Comment by huntario** [comment]
> hi @huntario changes in your PR are failing the bundling test - https://github.com/bigcommerce/cornerstone/runs/4976141414?check_suite_focus=true can you please check it?

My apologies, I see now that `npx grunt check` can be run locally to catch this before pushing. Thanks for catching this. I've updated it to pass.

**Review by yurytut1993 — APPROVED** [review]
Approved. Just a small suggestion to combine `margin` styles in one line. 
It can decrease final css file size

**Review by bc-alexsaiannyi — APPROVED** [review]

**Comment by huntario** [comment]
Thank you for the feedback. I've addressed the `margin` styles  note.

**Pull request merged**
