### PR TITLE
Add global region at the bottom of the navigation

### PR DESCRIPTION
**Pull request by bobbyshaw**
#### What?

Currently, it's not possible to add a widget to a global region within the header. The only available region is `header_bottom--global`. This is in the header template so is on all pages but is actually outside of the <header> element so may be styled differently resulting it feeling like it's below the header, not at the bottom of the header.

As an app developer, I would like to request at least one global region be added inside the header.

Happy for this to be a discussion on the best way to do this and it's appropriate to add further global regions too, e.g. top of this file as an alternative to banners.

#### Requirements

TBC

- [x] CHANGELOG.md entry added (required for code changes only)

### CODE REVIEW

**Comment by BC-krasnoshapka** [comment]
@bc-as what do you think about adding such region to header?

**Comment by bobbyshaw** [comment]
Hi @bc-as. We launched [a mega menu app](https://www.bigcommerce.com/apps/mega-menu-builder-by-space-48/). The current global header region mostly works but does mean that technically it's below (and outside of) the header, not "bottom" as described. As such, it can cause some styling issues.

**Comment by bc-as** [comment]
@bobbyshaw this looks fantastic!  I'm glad to see a creative use of regions!  @BC-krasnoshapka this seems like a great addition to Cornerstone, can we get this merged and released with the next version?

**Comment by BC-krasnoshapka** [comment]
Sure, no problem. @bobbyshaw can you please update CHANGELOG also?

**Comment by bobbyshaw** [comment]
@BC-krasnoshapka I have updated the CHANGELOG.

**Review by BC-krasnoshapka — APPROVED** [review]

**Comment by BC-krasnoshapka** [comment]
Thanks. LGTM

**Pull request merged**
