### PR TITLE
fix(storefront): BCTHEME-139 Unnecessary heading tag in carousel

### PR DESCRIPTION
**Pull request by BC-tymurbiedukhin**
#### What?

Each slide in the homepage carousel contains an h1 tag for the slide headings.  These headings are inconsistent with guidelines for page hierarchy. Instead of h1 tags, carousel headings should be h3 or h4

#### Tickets / Documentation

[Jira Ticket](https://jira.bigcommerce.com/browse/BCTHEME-139)

#### Screenshots (if appropriate)

Screenshot 2020-08-12 at 11 09 28

### CODE REVIEW

**Comment by mattcoy-arcticleaf** [comment]
@BC-tymurbiedukhin , can it be an h3 when there might not be an h2 before it?

**Comment by BC-tymurbiedukhin** [comment]
@mattcoy-arcticleaf We have h2 tags for more important sections below

**Comment by mattcoy-arcticleaf** [comment]
@BC-tymurbiedukhin , but you cannot have an h3 on a page without having an h2 to give it context. If there is no h2 as a section title for this section, you can't use an h3 inside it. I'm not saying the slides should be h2's, I'm saying the current setup is invalid as well.

**Comment by BC-tymurbiedukhin** [comment]
@mattcoy-arcticleaf @bc-as Tag was changed from h3 to span according to page semantic rules

**Review by yurytut1993 — APPROVED** [review]

**Pull request merged**
