### PR TITLE
CHECKOUT-2314 Add footer scripts to optimized checkout

### PR DESCRIPTION
**Pull request by icatalina**
#### What?

Add footer scripts to optimized checkout

#### Tickets / Documentation

https://jira.bigcommerce.com/browse/CHECKOUT-2314

@bigcommerce/checkout @junedkazi @mjschock

### CODE REVIEW

**Comment by PascalZajac** [comment]
Do we need to add this to order confirmation as well?

**Comment by PreciselyAlyss** [comment]
@PascalZajac I would love it if it was

**Comment by icatalina** [comment]
Good point! :)

**Comment by icatalina** [comment]
Sorted @PascalZajac & @PreciselyAlyss  :)

**Pull request merged**
