### PR TITLE
STRF-8948 Fix Sort By on Search Page

### PR DESCRIPTION
**Pull request by jairo-bc**
#### What?

Updated Stencil Utils to 6.8.1 and removed changes from https://github.com/bigcommerce/cornerstone/pull/1910/files

#### Tickets / Documentation

Add links to any relevant tickets and documentation.

- [STRF-8948](https://jira.bigcommerce.com/browse/STRF-8948)

### CODE REVIEW

**Comment by BC-tymurbiedukhin** [comment]
Could we add screenshot/video with fix verifying?

**Comment by jairo-bc** [comment]
https://user-images.githubusercontent.com/68893868/105834329-01ed5000-5fd3-11eb-9652-eded6e0c8bb4.mov

**Comment by jairo-bc** [comment]
https://user-images.githubusercontent.com/68893868/105834478-2f39fe00-5fd3-11eb-9ebe-d45e12a395cd.mov

**Comment by jairo-bc** [comment]
@BC-tymurbiedukhin added videos with and without Product Filters

**Comment by yurytut1993** [comment]
@jairo-bc can you please also videos with posts sorting?
Also is it okey with pagination? When we have for example 2 pages with products and 1 page with posts and we are trying to go to the posts from second page of products, will we see posts?

**Comment by jairo-bc** [comment]
https://user-images.githubusercontent.com/68893868/106445745-14aacd80-6488-11eb-8e81-e53488b5141a.mov

Video for posts sorting

**Comment by jairo-bc** [comment]
@yurytut1993 I think pagination is a separate bug, cause we are not tracking separately the second tab page number.

**Comment by BC-tymurbiedukhin** [comment]
Could we log the separate JIra for pagination bug?

**Comment by jairo-bc** [comment]
> Could we log the separate JIra for pagination bug?

https://jira.bigcommerce.com/browse/BCTHEME-396

**Comment by BC-tymurbiedukhin** [comment]
LGTM

**Review by BC-tymurbiedukhin — APPROVED** [review]
LGTM

**Review by yurytut1993 — APPROVED** [review]

**Pull request merged**
