### PR TITLE
Fix social sharing links for product pages and blog posts

### LINKED ISSUE #2081: Social sharing broken
### Expected behavior
Social sharing links on product pages should link to social sites with the url included

### Actual behavior
Social sharing links have the url as undefined

### Steps to reproduce behavior
Browse to any product page and click on a social share link

### References

addthis support was removed in https://github.com/bigcommerce/cornerstone/pull/1997 and `product.url` is now passed in as `url` on [line 252](https://github.com/bigcommerce/cornerstone/pull/1997/files#diff-5c578dd3f6c319663a11fd74d740442bc765e2371934ce7dc3c36b40bf59db65R252)

#2077 fixed this for blog posts but breaks it for product pages. i believe the correct fix would be to pass in `post.url` as `url` to the share component

```
$ ag 'common/share'
templates/components/products/product-view.html
279:        {{> components/common/share url=product.url}}

templates/components/blog/post.html
48:        {{>components/common/share}}

[some removed]
```

### PR DESCRIPTION
**Pull request by rowleyaj**
#### What?

Fixes #2081 

#### Tickets / Documentation

- [2081](https://github.com/bigcommerce/cornerstone/issues/2081)
- [1997](https://github.com/bigcommerce/cornerstone/pull/1997)
- [2077](https://github.com/bigcommerce/cornerstone/pull/2077)
- [STRF-9126](https://jira.bigcommerce.com/browse/STRF-9126)

### CODE REVIEW

**Comment by rowleyaj** [comment]
cc @jairo-bc as the original PR author

**Review by jairo-bc — APPROVED** [review]

**Comment by rowleyaj** [comment]
@BC-tymurbiedukhin please can you take a look at this PR?

**Review by BC-tymurbiedukhin — APPROVED** [review]
LGTM

**Comment by BC-tymurbiedukhin** [comment]
@bc-azvierieva Could you please verify from your side?

**Comment by rowleyaj** [comment]
@bc-azvierieva i've fixed the conflicts with the master branch, they were just changes in the changelog

**Comment by rowleyaj** [comment]
@BC-tymurbiedukhin @bc-azvierieva do you think we can get this merged today please? i keep having to fix conflicts in the changelog to keep the PR current as other things are merged in.

i'd really like to get it into the next release as the prior fix in 5.6.0 fixed blog posts but broke it for products. please let me know if you need any more information to help test

**Comment by bc-azvierieva** [comment]
> @BC-tymurbiedukhin @bc-azvierieva do you think we can get this merged today please? i keep having to fix conflicts in the changelog to keep the PR current as other things are merged in.
> 
> i'd really like to get it into the next release as the prior fix in 5.6.0 fixed blog posts but broke it for products. please let me know if you need any more information to help test

Hey Alex,
I've checked your fix, it works fine! I'll approve this PR now so I believe we can merge it cc @BC-tymurbiedukhin

**Review by bc-azvierieva — APPROVED** [review]

**Pull request merged**
